version: '3.8'

services:
  noisecapt:
    image: kx1t/noisecapt
    tty: true
    container_name: noisecapt
    hostname: noisecapt
    restart: always
    devices:
      - /dev/snd:/dev/snd
# you must expose this port if noisecapt doesnt run from the same
# docker-compose.yml as planefence:
#    ports:
#      - 30088:80
    environment:
# make sure that the timezones of noisecapt and planefence are the same
# otherwise things wont work
      - TZ=${FEEDER_TZ}
# Noisecapt produces lots of data. This is the retention time in hours
# If you make it more than 2 (hrs), you should also increase the tmpfs size
# for /run
      - PF_DELETEAFTER=1
# This defines the capure time blocks, you shpuld probably leave this alone:
      - PF_CAPTURETIME=5
#      - PF_AUDIOCARD=2
#      - PF_AUDIODEVICE=0
#      - PF_ALSA_MANUAL=ON
    tmpfs:
      - /run:rw,nosuid,nodev,exec,relatime,size=256M
      - /tmp:rw,nosuid,nodev,noexec,relatime,size=128M
