#!/command/with-contenv bash
#shellcheck shell=bash disable=SC1091,SC2154

source /scripts/common

"${s6wrap[@]}" echo "Cleanup started as an s6 service"

# -----------------------------------------------------------------------------------
# Copyright 2020-2024 Ramon F. Kolb - licensed under the terms and conditions
# of GPLv3. The terms and conditions of this license are included with the Github
# distribution of this package, and are also available here:
# https://github.com/kx1t/docker-planefence
#
# -----------------------------------------------------------------------------------
# Feel free to make changes to the variables between these two lines. However, it is
# STRONGLY RECOMMENDED to RTFM! See README.md for explanation of what these do.
#
# LOOPTIME is the time between two runs cleanup. In our case, daily.
LOOPTIME="1d"
#
# OLDERTHAN indicates which age files can be deleted. This is in DAYS.
# It specifically applies to files in the HTML directory.
# If $PF_DELETEAFTER is set to "0" then we never delete.
# Note - files in /tmp will get deleted if they are older than 2 days.
OLDERTHAN="${PF_DELETEAFTER:-14}"
#
# MAXLOGLINES contains the max number of lines that we will keep in /tmp/planefence.log
MAXLOGLINES=5000
#
# this function cleans out stuff. Make additions to it as needed.
CLEANUP ()
{
  if (( OLDERTHAN > 0 ))
  then
    find /tmp -mindepth 1 -mtime +2 -delete 2>/dev/null
    find /run/noisecapt/*.log -mtime +"$OLDERTHAN" -delete 2>/dev/null
    tail -n $MAXLOGLINES /run/noisecapt/noisecapt.log >/run/noisecapt/noisecapt.log.tmp 2>/dev/null
    mv -f /run/noisecapt/noisecapt.log.tmp /run/noisecapt/noisecapt.log 2>/dev/null
  else
    "${s6wrap[@]}" echo "$LOOPTIME set to 0 - cleanup skipped"
  fi
}
#
#Now loop forevah:
while true
do
  "${s6wrap[@]}" echo "Performing a cleanup run..."
  CLEANUP
  "${s6wrap[@]}" echo "Cleanup done. Sleeping for $LOOPTIME"
  sleep $LOOPTIME
done
