#!/command/with-contenv bash
#shellcheck shell=bash disable=SC1091,SC2154

source /scripts/common
"${s6wrap[@]}" echo "deployment started"

# -----------------------------------------------------------------------------------
# Copyright 2020-2025 Ramon F. Kolb - licensed under the terms and conditions
# of GPLv3. The terms and conditions of this license are included with the Github
# distribution of this package, and are also available here:
# https://github.com/kx1t/noisecapt/
#
# The package contains parts of, and modifications or derivatives to the following:
# Dump1090.Socket30003 by Ted Sluis: https://github.com/tedsluis/dump1090.socket30003
# These packages may incorporate other software and license terms.
#
# -----------------------------------------------------------------------------------
# Feel free to make changes to the variables between these two lines. However, it is
# STRONGLY RECOMMENDED to RTFM! See README.md for explanation of what these do.
#
# Make sure the /run directory exists
mkdir -p /run/noisecapt
# LOOPTIME is the time between two runs of noisecapt (in seconds)
# Since Noisecapt.sh already runs forever by itself, noisecapt is the time between a failure of the script, and
# the system trying to re-start it. This can safely be set to a few seconds.
LOOPTIME=10s
#
# NOISECAPTDIR contains the directory where noisecapt.sh is location
NOISECAPTDIR=/usr/share/noisecapt
# -----------------------------------------------------------------------------------
#
# Do some magic to try to ensure the soundcard is not muted:
#
# Get the card and device number from the .env file, or if not, extract it from arecord.
# The $PF_ALSA_MANUAL variable indicates that the user has done their own settings and we shouldn't touch them
if ! chk_enabled "$PF_ALSA_MANUAL"; then
		CARD="${PF_AUDIOCARD:-$(arecord --list-devices | sed  -n 's/.*card \([0-9][0-9]*\).*/\1/p')}"
	if [[ -n "$CARD" ]]; then
		# Figure out which NumID the mute button is unmute (which means set Mic Capture Switch = on):
		numid="$(amixer --card "$CARD" contents|grep 'Mic Capture Switch' | sed  -n 's/numid=\([0-9]\+\).*/\1/p')"
		amixer -c "$CARD" cset numid="$numid" on >/dev/null 2>&1
		#
		# Get the NumID and max value for the audio input level and max it out
		maxvolume="$(amixer --card "$CARD" contents|grep -A1 'Mic Capture Volume'| sed  -n 's/.*max=\([0-9]\+\).*/\1/p')"
		numid="$(amixer --card "$CARD" contents|grep 'Mic Capture Volume' | sed  -n 's/numid=\([0-9]\+\).*/\1/p')"
		amixer -q -c "$CARD" cset numid="$numid" "$maxvolume"
		# Last - switch the AGC off as this will mess with the audio levels
		numid="$(amixer --card "$CARD" contents|grep 'Auto Gain Control' | sed  -n 's/numid=\([0-9]\+\).*/\1/p')"
		if [[ -n "$numid" ]]; then amixer -q -c "$CARD" cset numid="$numid" off; fi
	fi
fi
# -----------------------------------------------------------------------------------
#

while true
do
	"${s6wrap[@]}" $NOISECAPTDIR/noisecapt.sh >/run/noisecapt/noisecapt.log
	"${s6wrap[@]}" echo "Noisecapt has exited unexpectedly... restarting in $LOOPTIME"
	sleep $LOOPTIME
	"${s6wrap[@]}" echo "Noisecapt restarting now"
done
